### ISSUE TITLE
gnutls

### ISSUE THREAD

**Issue by bAndie91** [hugsy/sstoper#4]
does it compile with gnutls 2.12.20 ?

**Comment by hugsy** [comment]
It should, however GnuTLS is not the recommended SSL library to be used for the tool. I highly recommend `mbedTLS` instead (formerly known as `PolarSSL`). 

If it does not compile, send a description of the behaviour.

Thanks.

**Comment by bAndie91** [comment]
compiling with polarssl 1.2.9 gives error:

```
In file included from main.c:63:0:
main.h:83:1: error: unknown type name ‘x509_crt’
```

**Comment by hugsy** [comment]
The version of `polarssl` you're using is too old.

**Comment by bAndie91** [comment]
Ok, it compiles with polarssl 1.3.9.
